import React, { useMemo } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Receipt } from 'lucide-react-native';
import type { Debt } from '@/features/debts/types';
import { ReceiptDottedRule } from '@/features/debts/receipt/ReceiptDottedRule';
import { ReceiptImageContainer } from '@/features/debts/receipt/ReceiptImageContainer';
import { ReceiptRow } from '@/features/debts/receipt/ReceiptRow';
import {
  ReceiptTearEdge,
  RECEIPT_TEAR_TOOTH_DEPTH,
} from '@/features/debts/receipt/ReceiptTearEdge';
import {
  RECEIPT_INK,
  RECEIPT_MIN_HEIGHT,
  RECEIPT_PAD_H,
  RECEIPT_PAPER,
  RECEIPT_SCRIM,
  RECEIPT_WIDTH,
  receiptType,
} from '@/features/debts/receipt/receiptTheme';
import { buildTransactionReceiptData } from '@/features/debts/receipt/transactionReceiptData';

interface TransactionThermalReceiptProps {
  debt: Debt;
  fmt: (amount: number) => string;
  backdropColor?: string;
  photoUri?: string | null;
}

export function TransactionThermalReceipt({
  debt,
  fmt,
  backdropColor = RECEIPT_SCRIM,
  photoUri,
}: TransactionThermalReceiptProps) {
  const data = useMemo(() => buildTransactionReceiptData(debt, fmt), [debt, fmt]);
  const hasPayments = data.paymentLines.length > 0;
  const hasPhoto = Boolean(photoUri);

  return (
    <View style={styles.wrapper}>
      <View style={styles.paper}>
        <View style={[styles.sideNotchLeft, { backgroundColor: backdropColor }]} />
        <View style={[styles.sideNotchRight, { backgroundColor: backdropColor }]} />

        <View style={styles.body}>

          {/* ── Top bar: icon | "Transaction Receipt" ── */}
          <View style={styles.topBar}>
            <Receipt size={15} color={RECEIPT_INK} strokeWidth={2.5} />
            <Text style={styles.headerLabel}>Transaction Receipt</Text>
          </View>

          <ReceiptDottedRule />

          {/* ── Hero row: name + type | amount + date ── */}
          <View style={styles.heroRow}>
            <View style={styles.heroLeft}>
              <Text style={styles.heroTitle} numberOfLines={2}>
                {data.heroLeft.title}
              </Text>
              <Text style={styles.heroSubtitle}>{data.heroLeft.subtitle}</Text>
            </View>
            <View style={styles.heroRight}>
              <Text style={styles.heroTitle} numberOfLines={1}>
                {data.heroRight.title}
              </Text>
              <Text style={styles.heroSubtitleRight}>{data.heroRight.subtitle}</Text>
            </View>
          </View>

          {/* ── Transaction ID (inline, no extra dividers) ── */}
          <Text style={styles.transactionId}>{data.referenceId}</Text>

          {/* ── Image container (only when a photo is attached) ── */}
          {hasPhoto ? (
            <View style={styles.mediaBlock}>
              <ReceiptImageContainer uri={photoUri} />
              <View style={styles.stamp}>
                <Text style={styles.stampText}>CERTIFIED</Text>
              </View>
            </View>
          ) : null}

          <ReceiptDottedRule />

          {/* ── Debt rows ── */}
          {data.rows.map((row) => (
            <ReceiptRow key={row.label} row={row} />
          ))}

          {/* ── Payments ── */}
          {hasPayments ? (
            <>
              <ReceiptDottedRule />
              <Text style={styles.subsection}>Payments</Text>
              {data.paymentLines.map((row, index) => (
                <ReceiptRow key={`${row.label}-${index}`} row={row} />
              ))}
            </>
          ) : null}

          <View style={styles.bodyGrow} />

          {/* ── Footer with cut-line divider ── */}
          <ReceiptDottedRule />
          <View style={styles.footer}>
            <Text style={styles.footerWordmark}>DEBTLY</Text>
            <Text style={styles.footerTagline}>Generated by Debtly</Text>
          </View>
        </View>
      </View>

      <View style={styles.tear}>
        <ReceiptTearEdge
          width={RECEIPT_WIDTH}
          color={RECEIPT_PAPER}
          backdropColor={backdropColor}
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  wrapper: {
    width: RECEIPT_WIDTH,
    alignSelf: 'center',
  },
  paper: {
    width: RECEIPT_WIDTH,
    minHeight: RECEIPT_MIN_HEIGHT - RECEIPT_TEAR_TOOTH_DEPTH,
    backgroundColor: RECEIPT_PAPER,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    overflow: 'hidden',
  },
  body: {
    flexGrow: 1,
    paddingHorizontal: RECEIPT_PAD_H,
    paddingTop: 18,
    paddingBottom: 18,
  },

  /* Top bar */
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLabel: receiptType.headerLabel,

  /* Hero */
  heroRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  heroLeft: {
    flex: 1,
  },
  heroRight: {
    alignItems: 'flex-end',
  },
  heroTitle: receiptType.heroTitle,
  heroSubtitle: receiptType.heroSubtitle,
  heroSubtitleRight: {
    ...receiptType.heroSubtitle,
    textAlign: 'right',
  },

  /* Image */
  mediaBlock: {
    position: 'relative',
    alignSelf: 'stretch',
    marginTop: 14,
  },
  stamp: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: RECEIPT_INK,
    borderRadius: 999,
    transform: [{ rotate: '-8deg' }],
    paddingVertical: 3,
    paddingHorizontal: 8,
    backgroundColor: RECEIPT_PAPER,
  },
  stampText: receiptType.stamp,

  /* Transaction ID */
  transactionId: receiptType.transactionId,

  /* Payments */
  subsection: receiptType.subsection,

  /* Side notches */
  sideNotchLeft: {
    position: 'absolute',
    left: -6,
    top: '45%',
    width: 12,
    height: 12,
    borderRadius: 999,
    zIndex: 2,
  },
  sideNotchRight: {
    position: 'absolute',
    right: -6,
    top: '45%',
    width: 12,
    height: 12,
    borderRadius: 999,
    zIndex: 2,
  },

  bodyGrow: {
    flexGrow: 1,
    minHeight: 20,
  },

  /* Footer */
  footer: {
    alignItems: 'center',
    paddingTop: 12,
  },
  footerWordmark: receiptType.footer,
  footerTagline: receiptType.footerTagline,

  tear: {
    marginTop: -1,
  },
});
