import React, { useMemo } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Receipt } from 'lucide-react-native';
import type { Debt } from '@/features/debts/types';
import { ReceiptDottedRule } from '@/features/debts/receipt/ReceiptDottedRule';
import { ReceiptImageContainer } from '@/features/debts/receipt/ReceiptImageContainer';
import { ReceiptRow } from '@/features/debts/receipt/ReceiptRow';
import {
  ReceiptTearEdge,
  RECEIPT_TEAR_TOOTH_DEPTH,
} from '@/features/debts/receipt/ReceiptTearEdge';
import {
  RECEIPT_CONTENT_GAP,
  RECEIPT_INK,
  RECEIPT_PAD_H,
  RECEIPT_PAPER,
  RECEIPT_SCRIM,
  RECEIPT_WIDTH,
  receiptType,
} from '@/features/debts/receipt/receiptTheme';
import { buildTransactionReceiptData } from '@/features/debts/receipt/transactionReceiptData';

interface TransactionThermalReceiptProps {
  debt: Debt;
  fmt: (amount: number) => string;
  backdropColor?: string;
  photoUri?: string | null;
}

export function TransactionThermalReceipt({
  debt,
  fmt,
  backdropColor = RECEIPT_SCRIM,
  photoUri,
}: TransactionThermalReceiptProps) {
  const data = useMemo(() => buildTransactionReceiptData(debt, fmt), [debt, fmt]);
  const hasPayments = data.paymentLines.length > 0;
  const hasPhoto = Boolean(photoUri);
  const { header } = data;

  return (
    <View style={styles.wrapper}>
      <View style={styles.paper}>
        <View style={[styles.sideNotchLeft, { backgroundColor: backdropColor }]} />
        <View style={[styles.sideNotchRight, { backgroundColor: backdropColor }]} />

        <View style={styles.body}>
          <View style={styles.contentPad}>
            <View style={styles.topBar}>
              <Receipt size={15} color={RECEIPT_INK} strokeWidth={2.5} />
              <Text style={styles.headerLabel}>Debtly Receipt</Text>
            </View>
          </View>

          <ReceiptDottedRule />

          <View style={[styles.contentPad, styles.stack]}>
            <View style={styles.receiptHeaderRow}>
              <Text style={styles.receiptHeaderTitle} numberOfLines={2}>
                {header.title}
              </Text>
              <Text style={styles.receiptHeaderDate}>{header.date}</Text>
            </View>
            <ReceiptRow row={{ label: 'Receipt Id', value: data.referenceId }} />
            {hasPhoto ? (
              <View style={styles.mediaBlock}>
                <ReceiptImageContainer uri={photoUri!} />
                <View style={styles.stamp}>
                  <Text style={styles.stampText}>CERTIFIED</Text>
                </View>
              </View>
            ) : null}
          </View>

          <ReceiptDottedRule />

          <View style={[styles.contentPad, styles.stack]}>
            {data.rows.map((row) => (
              <ReceiptRow key={row.label} row={row} />
            ))}
          </View>

          {hasPayments ? (
            <>
              <ReceiptDottedRule />
              <View style={[styles.contentPad, styles.stack]}>
                <Text style={styles.subsection}>Payments</Text>
                {data.paymentLines.map((row, index) => (
                  <ReceiptRow key={`${row.label}-${index}`} row={row} />
                ))}
              </View>
            </>
          ) : null}

          <ReceiptDottedRule />

          <View style={[styles.contentPad, styles.stack]}>
            <ReceiptRow row={{ label: 'Amount', value: header.amount }} />
            <View style={styles.footer}>
              <Text style={styles.footerWordmark}>DEBTLY</Text>
              <Text style={styles.footerTagline}>Generated by Debtly</Text>
            </View>
          </View>
        </View>
      </View>

      <View style={styles.tear}>
        <ReceiptTearEdge
          width={RECEIPT_WIDTH}
          color={RECEIPT_PAPER}
          backdropColor={backdropColor}
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  wrapper: {
    width: RECEIPT_WIDTH,
    alignSelf: 'center',
  },
  paper: {
    width: RECEIPT_WIDTH,
    backgroundColor: RECEIPT_PAPER,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    overflow: 'hidden',
  },
  body: {
    paddingTop: 18,
    paddingBottom: 18,
  },
  contentPad: {
    paddingHorizontal: RECEIPT_PAD_H,
  },
  stack: {
    gap: RECEIPT_CONTENT_GAP,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLabel: receiptType.headerLabel,
  receiptHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  receiptHeaderTitle: receiptType.heroTitle,
  receiptHeaderDate: {
    ...receiptType.heroTitle,
    textAlign: 'right',
    flexShrink: 0,
  },
  mediaBlock: {
    position: 'relative',
    alignSelf: 'stretch',
  },
  stamp: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: RECEIPT_INK,
    borderRadius: 999,
    transform: [{ rotate: '-8deg' }],
    paddingVertical: 3,
    paddingHorizontal: 8,
    backgroundColor: RECEIPT_PAPER,
  },
  stampText: receiptType.stamp,
  subsection: {
    ...receiptType.subsection,
    marginTop: 0,
    marginBottom: 0,
  },
  sideNotchLeft: {
    position: 'absolute',
    left: -6,
    top: '45%',
    width: 12,
    height: 12,
    borderRadius: 999,
    zIndex: 2,
  },
  sideNotchRight: {
    position: 'absolute',
    right: -6,
    top: '45%',
    width: 12,
    height: 12,
    borderRadius: 999,
    zIndex: 2,
  },
  footer: {
    alignItems: 'center',
    paddingTop: 2,
  },
  footerWordmark: receiptType.footer,
  footerTagline: receiptType.footerTagline,
  tear: {
    marginTop: -1,
  },
});
