import { Debt } from '@/features/debts/types';
import { interestRateToBps } from '@/features/debts/interestEngine';

const now = new Date();
const d = (n: number) => new Date(now.getTime() + n * 864e5).toISOString();

export const INITIAL_DEBTS: Debt[] = [
  {
    id: 'mock-1',
    personName: 'Alex Johnson',
    principalMinor: 15000,
    type: 'owed_to_me',
    note: 'Lunch split at The Grove',
    dueDate: d(3).slice(0, 10),
    status: 'pending',
    interestRateBps: interestRateToBps(5),
    interestStartMode: 'immediate',
    interestAccrualFrequency: 'monthly',
    interestStartDate: now.toISOString().slice(0, 10),
    interestPaidMinor: 0,
    principalPaidMinor: 0,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    payments: [],
    recurringGroupId: 'mock-1',
    recurringSourceId: 'mock-1',
  },
  {
    id: 'mock-2',
    personName: 'Sarah Chen',
    principalMinor: 4550,
    type: 'owed_to_me',
    note: 'Movie tickets for Avatar',
    dueDate: d(-2).slice(0, 10),
    status: 'pending',
    interestPaidMinor: 0,
    principalPaidMinor: 2000,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    payments: [
      {
        id: 'mock-2-pay-1',
        amountMinor: 2000,
        interestAppliedMinor: 0,
        principalAppliedMinor: 2000,
        paidAt: d(-4),
        note: 'First installment',
      },
    ],
    recurringGroupId: 'mock-2',
    recurringSourceId: 'mock-2',
  },
  {
    id: 'mock-3',
    personName: 'Mike Rodriguez',
    principalMinor: 8000,
    type: 'i_owe',
    note: 'Uber rides last weekend',
    dueDate: d(7).slice(0, 10),
    status: 'pending',
    isRecurring: true,
    recurrenceInterval: 'monthly',
    recurrenceAnchorDate: d(7).slice(0, 10),
    nextCycleDate: d(7).slice(0, 10),
    interestPaidMinor: 0,
    principalPaidMinor: 0,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    payments: [],
    recurringGroupId: 'mock-3',
    recurringSourceId: 'mock-3',
  },
  {
    id: 'mock-4',
    personName: 'Emma Wilson',
    principalMinor: 20000,
    type: 'owed_to_me',
    note: 'Concert tickets advance',
    dueDate: d(-5).slice(0, 10),
    status: 'paid',
    paidAt: now.toISOString(),
    accruedInterestMinor: 0,
    interestPaidMinor: 0,
    principalPaidMinor: 20000,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    payments: [],
    recurringGroupId: 'mock-4',
    recurringSourceId: 'mock-4',
  },
  {
    id: 'mock-5',
    personName: 'James Park',
    principalMinor: 3500,
    type: 'i_owe',
    note: 'Coffee and snacks run',
    dueDate: d(14).slice(0, 10),
    status: 'pending',
    interestPaidMinor: 0,
    principalPaidMinor: 0,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    payments: [],
    recurringGroupId: 'mock-5',
    recurringSourceId: 'mock-5',
  },
];
